---
#- name: Clone dotfiles repository
#  git:
#    repo: https://github.com/sonnysideup/dotfiles.git
#    dest: ~/code/dotfiles

- name: Link dotfiles into home directory
  file:
    src: "~/code/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  loop:
    - .bash_profile
    - .gitconfig
    - .gitignore
    - .osx
    - .tmux.conf
    - .vimrc
