---
- name: Capture Homebrew installation path
  command: brew --prefix
  register: brew_prefix
  changed_when: false

- name: Tap AdoptOpenJDK
  homebrew_tap: name=adoptopenjdk/openjdk

- name: Install Homebrew packages
  homebrew: "name={{ item }}"
  loop:
    - circleci
    - colordiff
    - fzf
    - git
    - go
    - htop
    - helm
    - helm@2
    - hub
    - hugo
    - jq
    - kubernetes-cli
    - minikube
    - sbt
    - stern
    - terraform
    - tree
    - tmux
    - vim
    - watch

- name: Install Homebrew casks
  homebrew_cask: "name={{ item }}"
  loop:
    - 1password
    - adoptopenjdk8
    - alfred
    - dash
    - docker
    - iterm2
    - keybase
    - firefox
    - goland
    - intellij-idea-ce
    - macdown
    - ngrok
    - postman
    - pycharm-ce
    - slack
    - spotify
    - zoomus

- name: Capture Helm v2 installation path
  command: brew --prefix helm@2
  register: helm2_install_path
  changed_when: false

- name: Link Helm v2 binary
  file:
    src: "{{ helm2_install_path.stdout }}/bin/helm"
    dest: "{{ brew_prefix.stdout }}/bin/helm2"
    state: link
