---
- name: Install MAS CLI
  homebrew: name=mas state=present

- name: List installed MAS apps
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: Install MAS applications
  command: "mas install {{ item.id }}"
  when: (item.id | string) not in mas_list.stdout
  loop:
    - { id: 937984704, name: 'Amphetamine' }
    - { id: 506189836, name: 'Harvest' }
    - { id: 1475897096, name: 'Jira' }
    - { id: 540348655, name: 'Monosnap' }
    - { id: 1447569061, name: 'Pomo Timer' }
    - { id: 904280696, name: 'Things 3' }
    - { id: 1147396723, name: 'WhatsApp' }
