---
- name: Download helm installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /usr/local/bin/get_helm.sh
    mode: 0700

- name: Install helm
  become: yes
  command:
    cmd: get_helm.sh
    creates: /usr/local/bin/helm

- name: Helm repo list
  command: helm repo list
  register: helm_repo_list
  changed_when: false

- name: Add stable helm repository
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com
  when: "'stable' not in helm_repo_list.stdout"
