---
- name: Download k3s binary
  become: yes
  get_url:
    url: https://github.com/rancher/k3s/releases/download/v1.18.2+k3s1/k3s
    dest: /usr/local/bin/k3s
    mode: '0755'

# TODO: fix k3s install / uninstall; the installer script should cleanup
# resources a little better
