---
- name: Install kvm
  become: yes
  apt:
    pkg:
      - qemu-kvm
      - libvirt-daemon-system
      - bridge-utils

- name: Install minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
