---
- name: Install stern from binary releases
  become: yes
  get_url:
    url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
    dest: /usr/local/bin/stern
    mode: '0755'
