---
- name: Install basic packages
  become: yes
  apt:
    pkg:
      - colordiff
      - hub
      - htop
      - jq
      - tree
      - xclip

# TODO: install circleci cli
#
- name: Install yh
  become: yes
  unarchive:
    src: https://github.com/andreazorzetto/yh/releases/download/v0.2.1/yh-linux-amd64.zip
    dest: /usr/local/bin
    remote_src: yes
